### ISSUE TITLE
Shrink-AzDisk.ps1 - Issue with SKU and Zone on disk creation

### ISSUE THREAD

**Issue by jafin** [jrudlin/Azure#4]
Thanks for the great script, worked well, I had 1 issue.

With the New-Disk config, it didn't create the right SKU and didn't set a zone for the new disk.
Which then errors on attaching the disk to VM, due to incorrect Zone.

**Comment by jrudlin** [comment]
Hi @jafin, so what New-Disk parameters resolved it for you? Can you also share the error you got please? thanks

**Comment by jafin** [comment]
@jruidlin, apologies I should have taken more notice.  My VM had a Premium_LRS Sku and was in Zone 1.  When I Used the script, the disk Sku was different and the zone was Empty.  The error then was the VM was unable to attach the disk due to disk not being in zone 1.  Similar to this error https://docs.microsoft.com/en-us/answers/questions/1134/availability-set-to-availability-zone.html

As I was running the script in small cut/paste chunks, I had to adjust where the $diskconfig was assigned to include `-SkuName Premium_LRS`  and `-Zone=1`  (hardcoded to get me to a conclusion. I  didn't spend effort into what was involved in extracting these properties from the existing disk.. 

If I do require to perform this again, I will try to obtain more info.

**Comment by daviddelariva-trackglobe** [comment]
To solve this issue I suggest to change the cmdlet `New-AzDiskConfig`
So, it could be like this:

In line 57:
```
$diskZone = $Disk.Zones

$diskConfig = New-AzDiskConfig `
    -Location $VM.Location `
    -Zone $diskZone `
    -CreateOption Empty `
    -DiskSizeGB $DiskSizeGB `
    -HyperVGeneration $HyperVGen
```

In line 129:
`$diskConfig = New-AzDiskConfig -AccountType $accountType -Location $VM.location -Zone $diskZone -DiskSizeGB $DiskSizeGB -SourceUri $vhdUri -CreateOption Import -StorageAccountId $StorageAccount.Id -HyperVGeneration $HyperVGen`
